# Generated by Django 4.2.30 on 2026-05-19 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_number', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('company_category', models.CharField(blank=True, max_length=100)),
                ('company_status', models.CharField(blank=True, max_length=50)),
                ('country_of_origin', models.CharField(blank=True, max_length=100)),
                ('incorporated_on', models.DateField(blank=True, null=True)),
                ('accounts_ref_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('accounts_ref_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('accounts_last_made_up', models.DateField(blank=True, null=True)),
                ('accounts_category', models.CharField(blank=True, max_length=50)),
                ('sic_codes', models.JSONField(default=list)),
                ('needs_enrichment', models.BooleanField(default=True)),
                ('last_enriched_at', models.DateTimeField(blank=True, null=True)),
                ('enrichment_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['company_name', 'company_number'],
            },
        ),
        migrations.CreateModel(
            name='PSCEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psc_name', models.CharField(blank=True, max_length=255)),
                ('psc_kind', models.CharField(blank=True, max_length=100)),
                ('notified_on', models.DateField(blank=True, null=True)),
                ('ceased_on', models.DateField(blank=True, null=True)),
                ('nature_of_control', models.JSONField(default=list)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psc_events', to='core.company')),
            ],
            options={
                'ordering': ['-notified_on', 'psc_name'],
            },
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_code', models.CharField(blank=True, max_length=100)),
                ('holder_name', models.CharField(blank=True, max_length=255)),
                ('created_on', models.DateField(blank=True, null=True)),
                ('satisfied_on', models.DateField(blank=True, null=True)),
                ('charge_type', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='core.company')),
            ],
            options={
                'ordering': ['-created_on', 'charge_code'],
            },
        ),
    ]
